# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import artifact_pb2 as artifact__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artifact_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtifactServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadSourceBundle = channel.unary_stream(
                '/antcode.v1.ArtifactService/DownloadSourceBundle',
                request_serializer=artifact__pb2.SourceBundleDownloadRequest.SerializeToString,
                response_deserializer=artifact__pb2.ArtifactChunk.FromString,
                _registered_method=True)
        self.UploadTaskArtifact = channel.stream_unary(
                '/antcode.v1.ArtifactService/UploadTaskArtifact',
                request_serializer=artifact__pb2.ArtifactUploadFrame.SerializeToString,
                response_deserializer=artifact__pb2.ArtifactUploadResponse.FromString,
                _registered_method=True)
        self.ClaimRunOwnership = channel.unary_unary(
                '/antcode.v1.ArtifactService/ClaimRunOwnership',
                request_serializer=artifact__pb2.RunOwnershipClaimRequest.SerializeToString,
                response_deserializer=artifact__pb2.RunOwnershipClaimResponse.FromString,
                _registered_method=True)
        self.RenewRunOwnership = channel.unary_unary(
                '/antcode.v1.ArtifactService/RenewRunOwnership',
                request_serializer=artifact__pb2.RunOwnershipRenewRequest.SerializeToString,
                response_deserializer=artifact__pb2.RunOwnershipRenewResponse.FromString,
                _registered_method=True)
        self.ReleaseRunOwnership = channel.unary_unary(
                '/antcode.v1.ArtifactService/ReleaseRunOwnership',
                request_serializer=artifact__pb2.RunOwnershipReleaseRequest.SerializeToString,
                response_deserializer=artifact__pb2.RunOwnershipReleaseResponse.FromString,
                _registered_method=True)


class ArtifactServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadSourceBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadTaskArtifact(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimRunOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewRunOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseRunOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadSourceBundle': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadSourceBundle,
                    request_deserializer=artifact__pb2.SourceBundleDownloadRequest.FromString,
                    response_serializer=artifact__pb2.ArtifactChunk.SerializeToString,
            ),
            'UploadTaskArtifact': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadTaskArtifact,
                    request_deserializer=artifact__pb2.ArtifactUploadFrame.FromString,
                    response_serializer=artifact__pb2.ArtifactUploadResponse.SerializeToString,
            ),
            'ClaimRunOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimRunOwnership,
                    request_deserializer=artifact__pb2.RunOwnershipClaimRequest.FromString,
                    response_serializer=artifact__pb2.RunOwnershipClaimResponse.SerializeToString,
            ),
            'RenewRunOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewRunOwnership,
                    request_deserializer=artifact__pb2.RunOwnershipRenewRequest.FromString,
                    response_serializer=artifact__pb2.RunOwnershipRenewResponse.SerializeToString,
            ),
            'ReleaseRunOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseRunOwnership,
                    request_deserializer=artifact__pb2.RunOwnershipReleaseRequest.FromString,
                    response_serializer=artifact__pb2.RunOwnershipReleaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antcode.v1.ArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antcode.v1.ArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadSourceBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antcode.v1.ArtifactService/DownloadSourceBundle',
            artifact__pb2.SourceBundleDownloadRequest.SerializeToString,
            artifact__pb2.ArtifactChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadTaskArtifact(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/antcode.v1.ArtifactService/UploadTaskArtifact',
            artifact__pb2.ArtifactUploadFrame.SerializeToString,
            artifact__pb2.ArtifactUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimRunOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ArtifactService/ClaimRunOwnership',
            artifact__pb2.RunOwnershipClaimRequest.SerializeToString,
            artifact__pb2.RunOwnershipClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewRunOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ArtifactService/RenewRunOwnership',
            artifact__pb2.RunOwnershipRenewRequest.SerializeToString,
            artifact__pb2.RunOwnershipRenewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseRunOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ArtifactService/ReleaseRunOwnership',
            artifact__pb2.RunOwnershipReleaseRequest.SerializeToString,
            artifact__pb2.RunOwnershipReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
