# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\nantcode.v1\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xa4\x02\n\x12SpiderStatsSummary\x12\x15\n\rrequest_count\x18\x01 \x01(\x03\x12\x16\n\x0eresponse_count\x18\x02 \x01(\x03\x12\x1a\n\x12item_scraped_count\x18\x03 \x01(\x03\x12\x13\n\x0b\x65rror_count\x18\x04 \x01(\x03\x12\x16\n\x0e\x61vg_latency_ms\x18\x05 \x01(\x01\x12\x1b\n\x13requests_per_minute\x18\x06 \x01(\x01\x12\x45\n\x0cstatus_codes\x18\x07 \x03(\x0b\x32/.antcode.v1.SpiderStatsSummary.StatusCodesEntry\x1a\x32\n\x10StatusCodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\xdd\x01\n\x07Metrics\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0e\n\x06memory\x18\x02 \x01(\x02\x12\x0c\n\x04\x64isk\x18\x03 \x01(\x02\x12\x15\n\rrunning_tasks\x18\x04 \x01(\x05\x12\x1c\n\x14max_concurrent_tasks\x18\x05 \x01(\x05\x12\x12\n\ntask_count\x18\x06 \x01(\x05\x12\x15\n\rproject_count\x18\x07 \x01(\x05\x12\x11\n\tenv_count\x18\x08 \x01(\x05\x12\x34\n\x0cspider_stats\x18\n \x01(\x0b\x32\x1e.antcode.v1.SpiderStatsSummary\"[\n\x06OSInfo\x12\x0f\n\x07os_type\x18\x01 \x01(\t\x12\x12\n\nos_version\x18\x02 \x01(\t\x12\x16\n\x0epython_version\x18\x03 \x01(\t\x12\x14\n\x0cmachine_arch\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPIDERSTATSSUMMARY_STATUSCODESENTRY']._loaded_options = None
  _globals['_SPIDERSTATSSUMMARY_STATUSCODESENTRY']._serialized_options = b'8\001'
  _globals['_TIMESTAMP']._serialized_start=28
  _globals['_TIMESTAMP']._serialized_end=71
  _globals['_SPIDERSTATSSUMMARY']._serialized_start=74
  _globals['_SPIDERSTATSSUMMARY']._serialized_end=366
  _globals['_SPIDERSTATSSUMMARY_STATUSCODESENTRY']._serialized_start=316
  _globals['_SPIDERSTATSSUMMARY_STATUSCODESENTRY']._serialized_end=366
  _globals['_METRICS']._serialized_start=369
  _globals['_METRICS']._serialized_end=590
  _globals['_OSINFO']._serialized_start=592
  _globals['_OSINFO']._serialized_end=683
# @@protoc_insertion_point(module_scope)
