# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/antcode.v1.ControlService/Register',
                request_serializer=control__pb2.RegisterRequest.SerializeToString,
                response_deserializer=control__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/antcode.v1.ControlService/Deregister',
                request_serializer=control__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=control__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.Lease = channel.unary_unary(
                '/antcode.v1.ControlService/Lease',
                request_serializer=control__pb2.LeaseRequest.SerializeToString,
                response_deserializer=control__pb2.LeaseResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/antcode.v1.ControlService/CancelTask',
                request_serializer=control__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=control__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/antcode.v1.ControlService/UpdateConfig',
                request_serializer=control__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=control__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)
        self.WatchControl = channel.unary_stream(
                '/antcode.v1.ControlService/WatchControl',
                request_serializer=control__pb2.WatchControlRequest.SerializeToString,
                response_deserializer=control__pb2.ControlEvent.FromString,
                _registered_method=True)
        self.AckControl = channel.unary_unary(
                '/antcode.v1.ControlService/AckControl',
                request_serializer=control__pb2.AckControlRequest.SerializeToString,
                response_deserializer=control__pb2.AckControlResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Worker lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lease(self, request, context):
        """Lease replaces periodic heartbeat as the liveness signal.
        Metrics piggy-back on the same call so we don't need a separate channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Task lifecycle control (synchronous, low-frequency).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchControl(self, request, context):
        """Reverse control channel: a long-lived server-streaming RPC the Worker
        opens once and receives ControlEvents on. Each event carries an event_id
        that the Worker AckControls back when it has applied (or rejected) the event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=control__pb2.RegisterRequest.FromString,
                    response_serializer=control__pb2.RegisterResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=control__pb2.DeregisterRequest.FromString,
                    response_serializer=control__pb2.DeregisterResponse.SerializeToString,
            ),
            'Lease': grpc.unary_unary_rpc_method_handler(
                    servicer.Lease,
                    request_deserializer=control__pb2.LeaseRequest.FromString,
                    response_serializer=control__pb2.LeaseResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=control__pb2.CancelTaskRequest.FromString,
                    response_serializer=control__pb2.CancelTaskResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=control__pb2.UpdateConfigRequest.FromString,
                    response_serializer=control__pb2.UpdateConfigResponse.SerializeToString,
            ),
            'WatchControl': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchControl,
                    request_deserializer=control__pb2.WatchControlRequest.FromString,
                    response_serializer=control__pb2.ControlEvent.SerializeToString,
            ),
            'AckControl': grpc.unary_unary_rpc_method_handler(
                    servicer.AckControl,
                    request_deserializer=control__pb2.AckControlRequest.FromString,
                    response_serializer=control__pb2.AckControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antcode.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antcode.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/Register',
            control__pb2.RegisterRequest.SerializeToString,
            control__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/Deregister',
            control__pb2.DeregisterRequest.SerializeToString,
            control__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/Lease',
            control__pb2.LeaseRequest.SerializeToString,
            control__pb2.LeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/CancelTask',
            control__pb2.CancelTaskRequest.SerializeToString,
            control__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/UpdateConfig',
            control__pb2.UpdateConfigRequest.SerializeToString,
            control__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antcode.v1.ControlService/WatchControl',
            control__pb2.WatchControlRequest.SerializeToString,
            control__pb2.ControlEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.ControlService/AckControl',
            control__pb2.AckControlRequest.SerializeToString,
            control__pb2.AckControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
