# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTasks = channel.unary_stream(
                '/antcode.v1.DataService/StreamTasks',
                request_serializer=data__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=data__pb2.TaskDispatch.FromString,
                _registered_method=True)
        self.AckTask = channel.unary_unary(
                '/antcode.v1.DataService/AckTask',
                request_serializer=data__pb2.AckTaskRequest.SerializeToString,
                response_deserializer=data__pb2.AckTaskResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.stream_unary(
                '/antcode.v1.DataService/StreamStatus',
                request_serializer=data__pb2.TaskStatus.SerializeToString,
                response_deserializer=data__pb2.StatusAck.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/antcode.v1.DataService/StreamLogs',
                request_serializer=data__pb2.LogBatch.SerializeToString,
                response_deserializer=data__pb2.LogAck.FromString,
                _registered_method=True)
        self.StreamSpiderData = channel.stream_unary(
                '/antcode.v1.DataService/StreamSpiderData',
                request_serializer=data__pb2.SpiderDataBatch.SerializeToString,
                response_deserializer=data__pb2.SpiderDataAck.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTasks(self, request, context):
        """Task dispatch: server-streaming push. Worker opens this stream once with
        its capabilities + prefetch hint, and the Master/Gateway pushes TaskDispatch
        messages as they are scheduled. Replaces the legacy long-poll PollTask.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckTask(self, request, context):
        """Worker acknowledges accept/reject of a dispatched task (replaces AckTask).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request_iterator, context):
        """Task status updates flow back from Worker via client-streaming so each
        status transition (running -> completed/failed/...) reuses the same TCP
        connection. Replaces ReportResult + WorkerMessage.task_status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Single unified log path. A LogBatch can contain 1..N entries.
        Replaces SendLog + SendLogBatch + SendLogChunk - large payloads go via
        source_bundle (pgartifact://) instead of being chunked through gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSpiderData(self, request_iterator, context):
        """T6-T3: Rule/Spider scraped items flow. Client-streaming — Scrapy pipeline
        sends 1..N items per batch, gateway transcodes to Redis
        `{antcode}:spider:<run_id>:data` stream (same wire fields as direct mode).
        Batch MAY also carry a `meta` heartbeat (items_count / last_item_at) so
        batch_status_loop / test_service see real-time progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTasks,
                    request_deserializer=data__pb2.SubscribeRequest.FromString,
                    response_serializer=data__pb2.TaskDispatch.SerializeToString,
            ),
            'AckTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AckTask,
                    request_deserializer=data__pb2.AckTaskRequest.FromString,
                    response_serializer=data__pb2.AckTaskResponse.SerializeToString,
            ),
            'StreamStatus': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=data__pb2.TaskStatus.FromString,
                    response_serializer=data__pb2.StatusAck.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=data__pb2.LogBatch.FromString,
                    response_serializer=data__pb2.LogAck.SerializeToString,
            ),
            'StreamSpiderData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamSpiderData,
                    request_deserializer=data__pb2.SpiderDataBatch.FromString,
                    response_serializer=data__pb2.SpiderDataAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antcode.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antcode.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antcode.v1.DataService/StreamTasks',
            data__pb2.SubscribeRequest.SerializeToString,
            data__pb2.TaskDispatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.DataService/AckTask',
            data__pb2.AckTaskRequest.SerializeToString,
            data__pb2.AckTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/antcode.v1.DataService/StreamStatus',
            data__pb2.TaskStatus.SerializeToString,
            data__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/antcode.v1.DataService/StreamLogs',
            data__pb2.LogBatch.SerializeToString,
            data__pb2.LogAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSpiderData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/antcode.v1.DataService/StreamSpiderData',
            data__pb2.SpiderDataBatch.SerializeToString,
            data__pb2.SpiderDataAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
