# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """GatewayService handles all communication between Master and Worker
    (Previously named WorkerService)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerStream = channel.stream_stream(
                '/antcode.v1.GatewayService/WorkerStream',
                request_serializer=gateway__pb2.WorkerMessage.SerializeToString,
                response_deserializer=gateway__pb2.MasterMessage.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/antcode.v1.GatewayService/Register',
                request_serializer=gateway__pb2.RegisterRequest.SerializeToString,
                response_deserializer=gateway__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.PollTask = channel.unary_unary(
                '/antcode.v1.GatewayService/PollTask',
                request_serializer=gateway__pb2.PollTaskRequest.SerializeToString,
                response_deserializer=gateway__pb2.PollTaskResponse.FromString,
                _registered_method=True)
        self.AckTask = channel.unary_unary(
                '/antcode.v1.GatewayService/AckTask',
                request_serializer=gateway__pb2.AckTaskRequest.SerializeToString,
                response_deserializer=gateway__pb2.AckTaskResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/antcode.v1.GatewayService/ReportResult',
                request_serializer=gateway__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=gateway__pb2.ReportResultResponse.FromString,
                _registered_method=True)
        self.SendLog = channel.unary_unary(
                '/antcode.v1.GatewayService/SendLog',
                request_serializer=gateway__pb2.SendLogRequest.SerializeToString,
                response_deserializer=gateway__pb2.SendLogResponse.FromString,
                _registered_method=True)
        self.SendLogBatch = channel.unary_unary(
                '/antcode.v1.GatewayService/SendLogBatch',
                request_serializer=gateway__pb2.SendLogBatchRequest.SerializeToString,
                response_deserializer=gateway__pb2.SendLogBatchResponse.FromString,
                _registered_method=True)
        self.SendLogChunk = channel.unary_unary(
                '/antcode.v1.GatewayService/SendLogChunk',
                request_serializer=gateway__pb2.SendLogChunkRequest.SerializeToString,
                response_deserializer=gateway__pb2.SendLogChunkResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/antcode.v1.GatewayService/SendHeartbeat',
                request_serializer=gateway__pb2.SendHeartbeatRequest.SerializeToString,
                response_deserializer=gateway__pb2.SendHeartbeatResponse.FromString,
                _registered_method=True)
        self.PollControl = channel.unary_unary(
                '/antcode.v1.GatewayService/PollControl',
                request_serializer=gateway__pb2.PollControlRequest.SerializeToString,
                response_deserializer=gateway__pb2.PollControlResponse.FromString,
                _registered_method=True)
        self.AckControl = channel.unary_unary(
                '/antcode.v1.GatewayService/AckControl',
                request_serializer=gateway__pb2.AckControlRequest.SerializeToString,
                response_deserializer=gateway__pb2.AckControlResponse.FromString,
                _registered_method=True)
        self.ReportControlResult = channel.unary_unary(
                '/antcode.v1.GatewayService/ReportControlResult',
                request_serializer=gateway__pb2.ControlResultRequest.SerializeToString,
                response_deserializer=gateway__pb2.ControlResultResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """GatewayService handles all communication between Master and Worker
    (Previously named WorkerService)
    """

    def WorkerStream(self, request_iterator, context):
        """Bidirectional streaming for real-time communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Single call for worker registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollTask(self, request, context):
        """Worker polling for task dispatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckTask(self, request, context):
        """Worker task acknowledgment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Worker result reporting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLog(self, request, context):
        """Worker realtime logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Worker heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollControl(self, request, context):
        """Worker control polling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportControlResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerStream,
                    request_deserializer=gateway__pb2.WorkerMessage.FromString,
                    response_serializer=gateway__pb2.MasterMessage.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=gateway__pb2.RegisterRequest.FromString,
                    response_serializer=gateway__pb2.RegisterResponse.SerializeToString,
            ),
            'PollTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTask,
                    request_deserializer=gateway__pb2.PollTaskRequest.FromString,
                    response_serializer=gateway__pb2.PollTaskResponse.SerializeToString,
            ),
            'AckTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AckTask,
                    request_deserializer=gateway__pb2.AckTaskRequest.FromString,
                    response_serializer=gateway__pb2.AckTaskResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=gateway__pb2.ReportResultRequest.FromString,
                    response_serializer=gateway__pb2.ReportResultResponse.SerializeToString,
            ),
            'SendLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLog,
                    request_deserializer=gateway__pb2.SendLogRequest.FromString,
                    response_serializer=gateway__pb2.SendLogResponse.SerializeToString,
            ),
            'SendLogBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogBatch,
                    request_deserializer=gateway__pb2.SendLogBatchRequest.FromString,
                    response_serializer=gateway__pb2.SendLogBatchResponse.SerializeToString,
            ),
            'SendLogChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogChunk,
                    request_deserializer=gateway__pb2.SendLogChunkRequest.FromString,
                    response_serializer=gateway__pb2.SendLogChunkResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=gateway__pb2.SendHeartbeatRequest.FromString,
                    response_serializer=gateway__pb2.SendHeartbeatResponse.SerializeToString,
            ),
            'PollControl': grpc.unary_unary_rpc_method_handler(
                    servicer.PollControl,
                    request_deserializer=gateway__pb2.PollControlRequest.FromString,
                    response_serializer=gateway__pb2.PollControlResponse.SerializeToString,
            ),
            'AckControl': grpc.unary_unary_rpc_method_handler(
                    servicer.AckControl,
                    request_deserializer=gateway__pb2.AckControlRequest.FromString,
                    response_serializer=gateway__pb2.AckControlResponse.SerializeToString,
            ),
            'ReportControlResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportControlResult,
                    request_deserializer=gateway__pb2.ControlResultRequest.FromString,
                    response_serializer=gateway__pb2.ControlResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antcode.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antcode.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """GatewayService handles all communication between Master and Worker
    (Previously named WorkerService)
    """

    @staticmethod
    def WorkerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/antcode.v1.GatewayService/WorkerStream',
            gateway__pb2.WorkerMessage.SerializeToString,
            gateway__pb2.MasterMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/Register',
            gateway__pb2.RegisterRequest.SerializeToString,
            gateway__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/PollTask',
            gateway__pb2.PollTaskRequest.SerializeToString,
            gateway__pb2.PollTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/AckTask',
            gateway__pb2.AckTaskRequest.SerializeToString,
            gateway__pb2.AckTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/ReportResult',
            gateway__pb2.ReportResultRequest.SerializeToString,
            gateway__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/SendLog',
            gateway__pb2.SendLogRequest.SerializeToString,
            gateway__pb2.SendLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/SendLogBatch',
            gateway__pb2.SendLogBatchRequest.SerializeToString,
            gateway__pb2.SendLogBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/SendLogChunk',
            gateway__pb2.SendLogChunkRequest.SerializeToString,
            gateway__pb2.SendLogChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/SendHeartbeat',
            gateway__pb2.SendHeartbeatRequest.SerializeToString,
            gateway__pb2.SendHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/PollControl',
            gateway__pb2.PollControlRequest.SerializeToString,
            gateway__pb2.PollControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/AckControl',
            gateway__pb2.AckControlRequest.SerializeToString,
            gateway__pb2.AckControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportControlResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antcode.v1.GatewayService/ReportControlResult',
            gateway__pb2.ControlResultRequest.SerializeToString,
            gateway__pb2.ControlResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
